### ISSUE TITLE
"./configure" failing with error while building "libxc"

### ISSUE THREAD

**Issue by Soujanyajanga** [LLNL/inq#3]
Steps followed:

Step1: GIT Cloned the application using "git clone --recurse-submodules git@gitlab.com:Soujanya_Janga/inq.git"
Step2: cd inq
Step3: mkdir build cd build
Step4: ../configure --prefix=/opt/ms1_user/mohith/App/INQ/
Result:
cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/opt/ms1_user/mohith/App/INQ/ -DCMAKE_INSTALL_LIBDIR=/opt/ms1_user/mohith/App/INQ//lib
CMake version 3.22.1
CMake Warning (dev) at /usr/share/cmake-3.22/Modules/GNUInstallDirs.cmake:239 (message):
  Unable to determine default CMAKE_INSTALL_LIBDIR directory because no
  target architecture is known.  Please enable at least one language before
  including GNUInstallDirs.
Call Stack (most recent call first):
  CMakeLists.txt:4 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- downloading Catch2 v3p3

CONFIGURING LIBXC

-- Setting option CMAKE_BUILD_TYPE: Debug
-- Setting option BUILD_SHARED_LIBS: OFF
-- Setting option BUILD_TESTING: OFF
-- Setting option BUILD_FPIC: ON
-- Setting option NAMESPACE_INSTALL_INCLUDEDIR: /
-- Setting option ENABLE_GENERIC: OFF
-- Setting option ENABLE_FORTRAN: OFF
-- Setting option ENABLE_XHOST: ON
-- Performing Test CMAKE_C_FLAGS [-march=native] - Success, Appending
-- Performing Test CMAKE_CXX_FLAGS [-march=native] - Success, Appending
-- Setting option DISABLE_VXC: OFF
-- Setting option DISABLE_FXC: ON
-- Setting option DISABLE_KXC: ON
-- Setting option DISABLE_LXC: OFF
CMake Error at external_libs/libxc/cmake/autocmake_safeguards.cmake:16 (message):
  In-source builds not allowed.  Please run CMake from top directory and
  specify a build directory (e.g., cmake -H.  -Bbuild).
Call Stack (most recent call first):
  external_libs/libxc/CMakeLists.txt:48 (include)

-- Configuring incomplete, errors occurred!

**Comment by correaa** [comment]
I think it has to do with the relative git paths. 
Can you try cloning from `https://gitlab.com/npneq/inq.git`?

**Comment by Soujanyajanga** [comment]
Yes, tried cloning with

> https://gitlab.com/npneq/inq.git

Still the same issue observed

**Comment by xgupta** [comment]
> Step3: mkdir build cd build

This should be Step3: mkdir build && cd build

**Comment by correaa** [comment]
yes, it should.

 but where are you reading this from?

![image](https://user-images.githubusercontent.com/3047763/196053943-bb52745e-191d-45f9-9987-113b290138a7.png)

**Comment by xgupta** [comment]
> but where are you reading this from?

If you asking me, yeah read it from README and tried to help @Soujanyajanga.

**Comment by correaa** [comment]
Ah, yes I see. I didn't catch that detail in the original post. That must be the problem. @Soujanyajanga  Please fix that.
